spring:
  datasource:
    url: jdbc:mysql://j4c101.p.ssafy.io:3306/cooksistant?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use-new-id-generator-mappings: false
    generate-ddl: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
cloud:
  aws:
    credentials:
      accessKey: AKIAZH572DDMPGRMUQZ5
      secretKey: 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
    s3:
      bucket: s3-recipe-img/recipe_pic
    region:
      static: us-east-1
    stack:
      auto: false